
#ifndef _LCOM_I8042_H_
#define _LCOM_I8042_H_

/**
  * Constants for the i8042 Keyboard Controller.
  */

#define KBC_IRQ 0x1
#define TIMER_IRQ 0

#define MAX_NUM_TRIES 10


#define ESC_KEY 0x81



#define KBC_OUT_BUF 0x60 // PORT FOR OUTPUT AND INPUT REGISTERS
#define KBC_IN_BUF 0x60

#define KBC_COMMAND_PORT 0x64 // PORT FOR STATUS AND COMMAND REGISTER
#define KBC_STATUS_PORT 0x64

#define KBC_IBF BIT(1) // INPUT BUFFER FULL - DONT WRITE COMMANDS
#define KBC_OBF BIT(0) // OUTPUT BUFFER FULL - NOT AVAILABLE TO BE READ

// TO BE CHECKED IN THE IH (INTERRUPT HANDLER)
// BOTH REPRESENT ERRORS IN THE SERIAL COMMUNICATION

#define KBC_PAR_ERR BIT(7)
#define KBC_TO_ERR BIT(6)

#define SCAN_CODE_HEADER 0xE0 // FOR SCANCODES THAT USE TWO BYTES 

// COMMAND SECTION
// COMMANDS ARE WRITTEN IN THE 0x64 PORT
// ARGUMENTS ARE WRITTEN IN THE 0x60 PORT
#define READ_COMMAND_BYTE 0x20 // RETURNS COMMAND BYTE
#define WRITE_COMMAND_BYTE 0x60 // TAKES ARGUMENT TO PUT IN COMMAND BYTE
#define SELF_TEST 0xAA // 0x55 IF OK, 0xFC if ERROR
#define CHECK_INTERFACE 0xAB // RETURN 0 IF OK
  
// FOR CONFIGURATION PURPOSES
#define DISABLE_INTERFACE 0xAD 
#define ENABLE_INTERFACE 0xAE

// MAKE OR BREAK CODE BIT
#define MAKE_BIT BIT(7)

// COMMAND BYTE
// RESPONSIBLE FOR MANAGING INTERRUPTS AND SOME INTERFACES ASWELL
#define DISABLE_MOUSE_INTERFACE BIT(5)
#define DISABLE_KEYBOARD_INTERFACE BIT(4)
#define ENABLE_OBF_INT_MOUSE BIT(1)
#define ENABLE_OBF_INT_KEYBOARD BIT(0)

//DELAY
#define DELAY_US 20000

#endif
